spring.application.name: netflix-eureka-naming-server
server.port: 8761

spring.config.import: configserver:http://localhost:8888 # config server

eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false