apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders-service
spec:
  selector:
    app: orders-service
  type: NodePort
  ports:
  - port: 9100
    targetPort: http-orders
    nodePort: 30165 #30000-32767
    protocol: TCP
    name: http-orders
