apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-server-deployment
  labels:
    app: naming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naming-server
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
      - name: naming-server-deployment
        image: ricardoahumada/naming-server:0.0.1-SNAPSHOT
        ports:
        - name: http-ns
          containerPort: 8761