apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  type: NodePort
  ports:
  - port: 8888
    targetPort: http-cfg
    nodePort: 30164 #30000-32767
    protocol: TCP
    name: http-cfg
