spring:
   application:
      name: demoservice
server:
   port: 8080

---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9090

#debug: true
logging:
   path: /var/tmp/
   file: /var/tmp/mylog.log
#   level:
#      root: WARN

---
spring:
   profiles: prod
   application:
      name: demoservice
server:
   port: 4431
