apiVersion: v1
kind: Service
metadata:
  name: naming-server-service
  labels:
    app: naming-server
spec:
  selector:
    app: naming-server
  type: NodePort
  ports:
  - port: 8761
    targetPort: http-ns
    nodePort: 30165 #30000-32767
    protocol: TCP
    name: http-ns
