spring.application.name: limits-service
limits-service:
  minimum: 99
  maximum: 9999

# spring.config.import: "optional:configserver:" # NO config server
spring.config.import: configserver:http://localhost:8888 # config server

spring.profiles.active: dev #for activate dev profile
