apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  selector:
    app: products-service
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: http-prods
    nodePort: 30163 #30000-32767
    protocol: TCP
    name: http-prods
