apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
  labels:
    app: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service-deployment
          image: ricardoahumada/orders-service:v4
          env:
            - name: spring.config.import
              value: "optional:configserver:http://config-server:8888"
            - name: products-service.base-url
              value: "products-service:9090"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: dev-config.json
            - name: SECRETS_DEMO_USER_PASSWD
              valueFrom:
                secretKeyRef:
                  name: spring-security
                  key: spring.user.password
          ports:
            - name: http-orders
              containerPort: 9100