apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products-deployment
        image: ricardoahumada/products-service:0.0.1-SNAPSHOT
        ports:
        - name: http
          containerPort: 5000