spring:
   application:
      name: demoservice
   profiles.active: dev # active dev profile
server:
   port: 8080

---
spring:
   config.activate.on-profile: dev
   application:
      name: demoservice
server:
   port: 9090
   servlet.context-path: /api/v1

#debug: true
logging:
   path: /var/tmp/
   file: /var/tmp/mylog.log
#   level:
#      root: WARN

---
spring:
   config.activate.on-profile: prod
   application:
      name: demoservice
server:
   port: 4431
