server.port: 8765

spring:
  application.name: gateway-server
  security.oauth2.resourceserver.jwt.issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: ProductsService
          uri: "http://products-service:9090/"
          predicates:
            - Path=/products/**
          filters:
            - AddRequestHeader=added-request-header, added-request-header-value
            - AddResponseHeader=added-response-header, added-response-header-value
        - id: OrdersService
          uri: "http://orders-service:9100/"
          predicates:
            - Path=/orders/**
        - id: CustomersService
          uri: "http://customers-service:9200/"
          predicates:
            - Path=/customers/**


eureka.client:
  service-url.default-zone: http://localhost:8761/eureka
  health-check.enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

