apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  selector:
    app: gateway-server
  type: LoadBalancer
  ports:
  - port: 8765
    targetPort: http-gtw
    nodePort: 30166 #30000-32767
    protocol: TCP
    name: http-gtw
