apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-config
data:
  dev-config.json:
    '{
      "customers-service.base-url": "http://customers-service:9200",
      "accounts-service.maxtoshow": 3
     }'