apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  labels:
    app: accounts-service
spec:
  selector:
    app: accounts-service
  type: NodePort
  ports:
  - port: 9900
    targetPort: http-accounts
    nodePort: 30169 #30000-32767
    protocol: TCP
    name: http-accounts
