apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-deployment
  labels:
    app: accounts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
    spec:
      containers:
        - name: accounts-service-deployment
          image: ricardoahumada/accounts-service:v3
          env:
            - name: spring.config.import
              value: "optional:configserver:http://config-server:8888"
            - name: products-service.base-url
              value: "products-service:9090"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: accounts-config
                  key: dev-config.json
            - name: SECRETS_DEMO_USER_PASSWD
              valueFrom:
                secretKeyRef:
                  name: spring-security
                  key: spring.user.password
          ports:
            - name: http-accounts
              containerPort: 9900