version: '3.8'
services:
  config-server:
    image: ricardoahumada/config-server:0.0.1-SNAPSHOT
    build: config-server/
    container_name: config-server
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
  naming-server:
    image: ricardoahumada/naming-server:0.0.1-SNAPSHOT
    build: naming-server/
    container_name: naming-server
    depends_on:
      - config-server
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge      