server.port: 8765

spring:
  application.name: gateway-server
  security.oauth2.resourceserver.jwt.issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      discovery.locator.enabled: true
#      routes:
#        - id: ProductsService
#          uri: "lb://products-service/"
#          predicates:
#            - Path=/products/**
#          filters:
#            - AddRequestHeader=added-request-header, added-request-header-value
#            - AddResponseHeader=added-response-header, added-response-header-value
#        - id: OrdersService
#          uri: "lb://orders-service/"
#          predicates:
#            - Path=/orders/**


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /products-service/v3/api-docs
        name: Product Service
        primaryName: Product Service
      - url: /orders-service/v3/api-docs
        name: Order Service
        primaryName: Order Service
      - url: /accounts-service/v3/api-docs
        name: Account Service
        primaryName: Account Service

eureka.client:
  service-url.default-zone: http://localhost:8761/eureka
  health-check.enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

