apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders-deployment
        image: ricardoahumada/orders-service:0.0.1-SNAPSHOT
        ports:
        - name: http-orders
          containerPort: 9100