apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: orders
spec:
  selector:
    app: orders
  type: NodePort
  ports:
  - port: 9090
    targetPort: http
    nodePort: 30163 #30000-32767
    protocol: TCP
    name: http
